# Generated by Django 4.2.4 on 2023-08-30 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0003_seller_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='sale.product', verbose_name='продукты'),
        ),
    ]
